;; Packing and certification use exactly the JS f64 accumulation order.
(func (export "prepareGeneralBandLU") (param $matrix i32) (param $input i32) (param $scales i32) (param $starts i32) (param $ends i32) (param $offsets i32) (param $factor i32) (param $rhs i32) (param $right i32) (param $count i32) (param $stride i32) (param $kl i32) (param $shift f64) (result f64)
 (local $i i32) (local $j i32) (local $target i32) (local $source i32) (local $end i32) (local $maximum f64)
 (local.set $i (i32.const 0)) (block $end2 (loop $loop2 (br_if $end2 (i32.ge_s (local.get $i) (local.get $count)))
(f64.store (i32.add (local.get $rhs) (i32.mul (local.get $i) (i32.const 8))) (f64.mul (f64.neg (f64.load (i32.add (local.get $input) (i32.mul (local.get $i) (i32.const 8))))) (f64.load (i32.add (local.get $scales) (i32.mul (local.get $i) (i32.const 8))))))
(local.set $target (i32.sub (i32.add (i32.mul (local.get $i) (local.get $stride)) (local.get $kl)) (local.get $i)))
(local.set $source (i32.load (i32.add (local.get $offsets) (i32.mul (local.get $i) (i32.const 4)))))
(local.set $end (i32.add (i32.load (i32.add (local.get $ends) (i32.mul (local.get $i) (i32.const 4)))) (i32.const 1)))
(local.set $j (i32.load (i32.add (local.get $starts) (i32.mul (local.get $i) (i32.const 4))))) (block $end0 (loop $loop0 (br_if $end0 (i32.ge_s (local.get $j) (local.get $end)))
(f64.store (i32.add (local.get $factor) (i32.mul (i32.add (local.get $target) (local.get $j)) (i32.const 8))) (f64.mul (f64.mul (f64.load (i32.add (local.get $matrix) (i32.mul (i32.add (local.get $source) (local.get $j)) (i32.const 8)))) (f64.load (i32.add (local.get $scales) (i32.mul (local.get $i) (i32.const 8))))) (f64.load (i32.add (local.get $scales) (i32.mul (local.get $j) (i32.const 8))))))
(local.set $j (i32.add (local.get $j) (i32.const 1))) (br $loop0)))
(f64.store (i32.add (local.get $factor) (i32.mul (i32.add (local.get $target) (local.get $i)) (i32.const 8))) (f64.add (f64.load (i32.add (local.get $factor) (i32.mul (i32.add (local.get $target) (local.get $i)) (i32.const 8)))) (local.get $shift)))
(local.set $j (i32.load (i32.add (local.get $starts) (i32.mul (local.get $i) (i32.const 4))))) (block $end1 (loop $loop1 (br_if $end1 (i32.ge_s (local.get $j) (local.get $end)))
(local.set $maximum (f64.max (local.get $maximum) (f64.abs (f64.load (i32.add (local.get $factor) (i32.mul (i32.add (local.get $target) (local.get $j)) (i32.const 8)))))))
(local.set $j (i32.add (local.get $j) (i32.const 1))) (br $loop1)))
(local.set $i (i32.add (local.get $i) (i32.const 1))) (br $loop2)))
 (local.get $maximum))
(func (export "measureGeneralBandLU") (param $matrix i32) (param $input i32) (param $scales i32) (param $starts i32) (param $ends i32) (param $offsets i32) (param $factor i32) (param $rhs i32) (param $right i32) (param $count i32) (param $stride i32) (param $kl i32) (param $out i32) (param $shift f64)
 (local $i i32) (local $j i32) (local $target i32) (local $source i32) (local $end i32)
 (local $error f64) (local $rowNorm f64) (local $a f64) (local $residualNorm f64) (local $matrixNorm f64) (local $rhsNorm f64) (local $solutionNorm f64) (local $factorMaximum f64)
 (local.set $i (i32.const 0)) (block $end5 (loop $loop5 (br_if $end5 (i32.ge_s (local.get $i) (local.get $count)))
(local.set $error (f64.mul (f64.load (i32.add (local.get $input) (i32.mul (local.get $i) (i32.const 8)))) (f64.load (i32.add (local.get $scales) (i32.mul (local.get $i) (i32.const 8))))))
(local.set $rowNorm (f64.const 0))
(local.set $source (i32.load (i32.add (local.get $offsets) (i32.mul (local.get $i) (i32.const 4)))))
(local.set $end (i32.add (i32.load (i32.add (local.get $ends) (i32.mul (local.get $i) (i32.const 4)))) (i32.const 1)))
(local.set $j (i32.load (i32.add (local.get $starts) (i32.mul (local.get $i) (i32.const 4))))) (block $end3 (loop $loop3 (br_if $end3 (i32.ge_s (local.get $j) (local.get $end)))
(local.set $a (f64.add (f64.mul (f64.mul (f64.load (i32.add (local.get $matrix) (i32.mul (i32.add (local.get $source) (local.get $j)) (i32.const 8)))) (f64.load (i32.add (local.get $scales) (i32.mul (local.get $i) (i32.const 8))))) (f64.load (i32.add (local.get $scales) (i32.mul (local.get $j) (i32.const 8))))) (if (result f64) (i32.eq (local.get $i) (local.get $j)) (then (local.get $shift)) (else (f64.const 0)))))
(local.set $error (f64.add (local.get $error) (f64.mul (local.get $a) (f64.load (i32.add (local.get $rhs) (i32.mul (local.get $j) (i32.const 8)))))))
(local.set $rowNorm (f64.add (local.get $rowNorm) (f64.abs (local.get $a))))
(local.set $j (i32.add (local.get $j) (i32.const 1))) (br $loop3)))
(local.set $residualNorm (f64.max (local.get $residualNorm) (f64.abs (local.get $error))))
(local.set $matrixNorm (f64.max (local.get $matrixNorm) (local.get $rowNorm)))
(local.set $rhsNorm (f64.max (local.get $rhsNorm) (f64.abs (f64.mul (f64.load (i32.add (local.get $input) (i32.mul (local.get $i) (i32.const 8)))) (f64.load (i32.add (local.get $scales) (i32.mul (local.get $i) (i32.const 8))))))))
(local.set $solutionNorm (f64.max (local.get $solutionNorm) (f64.abs (f64.load (i32.add (local.get $rhs) (i32.mul (local.get $i) (i32.const 8)))))))
(local.set $target (i32.sub (i32.add (i32.mul (local.get $i) (local.get $stride)) (local.get $kl)) (local.get $i)))
(local.set $j (local.get $i)) (block $end4 (loop $loop4 (br_if $end4 (i32.ge_s (local.get $j) (i32.add (i32.load (i32.add (local.get $right) (i32.mul (local.get $i) (i32.const 4)))) (i32.const 1))))
(local.set $factorMaximum (f64.max (local.get $factorMaximum) (f64.abs (f64.load (i32.add (local.get $factor) (i32.mul (i32.add (local.get $target) (local.get $j)) (i32.const 8)))))))
(local.set $j (i32.add (local.get $j) (i32.const 1))) (br $loop4)))
(local.set $i (i32.add (local.get $i) (i32.const 1))) (br $loop5)))
 (f64.store (i32.add (local.get $out) (i32.mul (i32.const 0) (i32.const 8))) (local.get $residualNorm))
(f64.store (i32.add (local.get $out) (i32.mul (i32.const 1) (i32.const 8))) (local.get $matrixNorm))
(f64.store (i32.add (local.get $out) (i32.mul (i32.const 2) (i32.const 8))) (local.get $rhsNorm))
(f64.store (i32.add (local.get $out) (i32.mul (i32.const 3) (i32.const 8))) (local.get $solutionNorm))
(f64.store (i32.add (local.get $out) (i32.mul (i32.const 4) (i32.const 8))) (local.get $factorMaximum)))
(func (export "measureOriginalBandResidual") (param $matrix i32) (param $input i32) (param $solution i32) (param $starts i32) (param $ends i32) (param $offsets i32) (param $error i32) (param $count i32) (result f64)
 (local $i i32) (local $j i32) (local $source i32) (local $value f64) (local $maximum f64)
 (local.set $i (i32.const 0)) (block $end7 (loop $loop7 (br_if $end7 (i32.ge_s (local.get $i) (local.get $count)))
(local.set $value (f64.load (i32.add (local.get $input) (i32.mul (local.get $i) (i32.const 8)))))
(local.set $source (i32.load (i32.add (local.get $offsets) (i32.mul (local.get $i) (i32.const 4)))))
(local.set $j (i32.load (i32.add (local.get $starts) (i32.mul (local.get $i) (i32.const 4))))) (block $end6 (loop $loop6 (br_if $end6 (i32.ge_s (local.get $j) (i32.add (i32.load (i32.add (local.get $ends) (i32.mul (local.get $i) (i32.const 4)))) (i32.const 1))))
(local.set $value (f64.add (local.get $value) (f64.mul (f64.load (i32.add (local.get $matrix) (i32.mul (i32.add (local.get $source) (local.get $j)) (i32.const 8)))) (f64.load (i32.add (local.get $solution) (i32.mul (local.get $j) (i32.const 8)))))))
(local.set $j (i32.add (local.get $j) (i32.const 1))) (br $loop6)))
(f64.store (i32.add (local.get $error) (i32.mul (local.get $i) (i32.const 8))) (local.get $value))
(local.set $maximum (f64.max (local.get $maximum) (f64.abs (local.get $value))))
(local.set $i (i32.add (local.get $i) (i32.const 1))) (br $loop7)))
 (local.get $maximum))
(func (export "equilibrateGeneralBand") (param $matrix i32) (param $starts i32) (param $ends i32) (param $offsets i32) (param $scales i32) (param $count i32)
 (local $i i32) (local $j i32) (local $source i32) (local $maximum f64)
 (local.set $i (i32.const 0)) (block $end9 (loop $loop9 (br_if $end9 (i32.ge_s (local.get $i) (local.get $count)))
(local.set $maximum (f64.const 0))
(local.set $source (i32.load (i32.add (local.get $offsets) (i32.mul (local.get $i) (i32.const 4)))))
(local.set $j (i32.load (i32.add (local.get $starts) (i32.mul (local.get $i) (i32.const 4))))) (block $end8 (loop $loop8 (br_if $end8 (i32.ge_s (local.get $j) (i32.add (i32.load (i32.add (local.get $ends) (i32.mul (local.get $i) (i32.const 4)))) (i32.const 1))))
(local.set $maximum (f64.max (local.get $maximum) (f64.abs (f64.load (i32.add (local.get $matrix) (i32.mul (i32.add (local.get $source) (local.get $j)) (i32.const 8)))))))
(local.set $j (i32.add (local.get $j) (i32.const 1))) (br $loop8)))
(f64.store (i32.add (local.get $scales) (i32.mul (local.get $i) (i32.const 8))) (f64.div (f64.const 1) (f64.sqrt (f64.max (local.get $maximum) (f64.const 1e-30)))))
(local.set $i (i32.add (local.get $i) (i32.const 1))) (br $loop9))))

;; Retained factors certify in original units. Match the JS accumulation order
;; and norms exactly, including non-finite propagation through f64.max.
(func (export "measureOriginalBandBackwardError")
 (param $matrix i32) (param $input i32) (param $solution i32)
 (param $starts i32) (param $ends i32) (param $offsets i32)
 (param $out i32) (param $count i32)
 (local $i i32) (local $j i32) (local $source i32) (local $end i32)
 (local $v f64) (local $row f64) (local $a f64)
 (local $err f64) (local $normA f64) (local $normF f64) (local $normX f64)
 (block $done (loop $rows
  (br_if $done (i32.ge_s (local.get $i) (local.get $count)))
  (local.set $v (f64.load (i32.add (local.get $input) (i32.mul (local.get $i) (i32.const 8)))))
  (local.set $row (f64.const 0))
  (local.set $source (i32.load (i32.add (local.get $offsets) (i32.mul (local.get $i) (i32.const 4)))))
  (local.set $end (i32.load (i32.add (local.get $ends) (i32.mul (local.get $i) (i32.const 4)))))
  (local.set $j (i32.load (i32.add (local.get $starts) (i32.mul (local.get $i) (i32.const 4)))))
  (block $rowDone (loop $columns
   (br_if $rowDone (i32.gt_s (local.get $j) (local.get $end)))
   (local.set $a (f64.load (i32.add (local.get $matrix) (i32.mul (i32.add (local.get $source) (local.get $j)) (i32.const 8)))))
   (local.set $v (f64.add (local.get $v) (f64.mul (local.get $a) (f64.load (i32.add (local.get $solution) (i32.mul (local.get $j) (i32.const 8)))))))
   (local.set $row (f64.add (local.get $row) (f64.abs (local.get $a))))
   (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $columns)))
  (local.set $err (f64.max (local.get $err) (f64.abs (local.get $v))))
  (local.set $normA (f64.max (local.get $normA) (local.get $row)))
  (local.set $normF (f64.max (local.get $normF) (f64.abs (f64.load (i32.add (local.get $input) (i32.mul (local.get $i) (i32.const 8)))))))
  (local.set $normX (f64.max (local.get $normX) (f64.abs (f64.load (i32.add (local.get $solution) (i32.mul (local.get $i) (i32.const 8)))))))
  (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $rows)))
 (f64.store (local.get $out) (local.get $err))
 (f64.store (i32.add (local.get $out) (i32.const 8)) (local.get $normA))
 (f64.store (i32.add (local.get $out) (i32.const 16)) (local.get $normF))
 (f64.store (i32.add (local.get $out) (i32.const 24)) (local.get $normX)))
