const INCH_TO_MM = 25.4;
const FRENCH_DIAMETER_MM = 1 / 3;

export const GUIDEWIRE_DIAMETER_IN = 0.035;
export const GUIDEWIRE_DIAMETER_MM = GUIDEWIRE_DIAMETER_IN * INCH_TO_MM;
export const GUIDEWIRE_RADIUS_MM = GUIDEWIRE_DIAMETER_MM / 2;
export const GUIDEWIRE_RENDER_RADIUS_MM = GUIDEWIRE_RADIUS_MM * 0.5;

export const INTRODUCER_SHEATH_FRENCH = 6;
export const INTRODUCER_SHEATH_DIAMETER_MM = INTRODUCER_SHEATH_FRENCH * FRENCH_DIAMETER_MM;
export const INTRODUCER_SHEATH_RADIUS_MM = INTRODUCER_SHEATH_DIAMETER_MM / 2;
export const INTRODUCER_SHEATH_INNER_DIAMETER_MM = 1.80;
export const INTRODUCER_SHEATH_INNER_RADIUS_MM = INTRODUCER_SHEATH_INNER_DIAMETER_MM / 2;

export const PIGTAIL_CATHETER_FRENCH = 5;
export const PIGTAIL_CATHETER_DIAMETER_MM = PIGTAIL_CATHETER_FRENCH * FRENCH_DIAMETER_MM;
export const PIGTAIL_CATHETER_RADIUS_MM = PIGTAIL_CATHETER_DIAMETER_MM / 2;
export const PIGTAIL_CATHETER_INNER_DIAMETER_MM = 0.97;
export const PIGTAIL_CATHETER_INNER_RADIUS_MM = PIGTAIL_CATHETER_INNER_DIAMETER_MM / 2;
export const PIGTAIL_CATHETER_RENDER_RADIUS_MM = PIGTAIL_CATHETER_RADIUS_MM * 0.78;
